name: Deploy Next.js Application

on:
  push:
    branches:
      - main  # Trigger workflow on push to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the source code
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Create .env file
        run: 
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env && echo "MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}" >> .env && echo "RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}" >> .env && echo "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}" >> .env && echo "NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}" >> .env && echo "CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }}" >> .env && echo "CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}" >> .env && echo "CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}" >> .env && echo "CLOUDINARY_URL=${{ secrets.CLOUDINARY_URL }}" >> .env
      - name: Set up Docker CLI
        uses: docker/setup-buildx-action@v2        
      - name: Build docker image
        run: docker build -t tanishq0514/recipeguruji .
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin      
      - name: Publish image to docker hub
        run: docker push tanishq0514/recipeguruji:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull tanishq0514/recipeguruji:latest
      - name: Delete old container
        run: docker rm -f recipeGuruji-container
      - name: Run docker container
        run: docker run -d -p 3000:3000 --name recipeGuruji-container tanishq0514/recipeguruji
      - name: Run new container
        run: |
          docker run -d \
            -p 3000:3000 \
            --name recipeGuruji-container \
            --env-file .env \  # Optional: Load environment variables from a file if needed
            tanishq0514/recipeguruji:latest

      # Step 4: Clean up unused Docker resources (optional but recommended)
      - name: Cleanup unused images
        run: docker image prune -f

      